server:
  port: 9090
  
spring:
  profiles:
    active:
    - default
    
  mail:
    default-encoding: UTF-8
    host: smtp.mailtrap.io
    username: ca4036e29f3869
    password: 99cd580b1ee1cc
    port: 2525
    protocol: smtp
    
# EMAIL SERVICE CONFIGURATION
  freemarker:
    template-loader-path:
    - classpath:/templates/mail
        
