#
#logging:
#  level:
#    org.springframework: INFO
#    root: WARN
#    org.hibernate: ERROR

    
spring:
  datasource:
    url: jdbc:mysql://us-cdbr-east-06.cleardb.net/ad_1c043ebbb005492
    username: b9499340b07e3c
    password: 657b8cdd
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  redis:
    host: redis-18716.c11.us-east-1-2.ec2.cloud.redislabs.com
    port: 18716
    password: 2xWlbXoSrN9OFlWBQKksmcVB7IHs9A7g

  
  jpa:
    hibernate:
      ddl-auto: update         
  

# MailGun SMTP Config
#  mail:
#    default-encoding: UTF-8
#    host: smtp.mailgun.org
#    username: postmaster@sandbox8a4c7ef33b1a4337b4be72d55d55f55b.mailgun.org
#    password: a6d2636d8efe6e7cbaf8d30349893c54-e5e67e3e-3909243d
#    port: 587 
#    protocol: smtp
    
  mail:
    default-encoding: UTF-8
    host: smtp.mailgun.org
    username: capmatch@mg.goldenmindsdaycare.com
    password: 691645977943f500ba6eb3f4b3008a5f-f7d0b107-e6c6c9d4
    port: 587 
    protocol: smtp
    
    


# Add application configuration    
client:
  config:
    routes:
      base-path: http://localhost:8080
      

app:
  config:
    session-idle-lifetime: 1200         # On the stage, sessions last 20 minutes when idle   
      