#logging:#  level:#    root: DEBUG
#
server:
  port: 5050
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stack-o?serverTimezone=UTC
    username: root
    password: B@naK!ng1
    
    data:
    - classpath:initialize.sql    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop         # For development purposes, always create and drop tables
  
  
  mail:
    default-encoding: UTF-8
    host: smtp.mailtrap.io
    username: ca4036e29f3869
    password: 99cd580b1ee1cc
    port: 2525
    protocol: smtp    
## MailGun SMTP Config   #  mail:#    default-encoding: UTF-8#    host: smtp.mailgun.org#    username: capmatch@mg.goldenmindsdaycare.com#    password: c3e6d00b49433efaa3d2ff54e848e41b-7fba8a4e-b9b8a3cd#    port: 587 #    protocol: smtp



# Add application configuration
client:
  config:
    routes:
      base-path: http://localhost:8080    
    
    
app:
  config:
    session-idle-lifetime: 1200      
      
#debug: true
