
spring:
  profiles:
    active:
    - dev
    
  mail:
    default-encoding: UTF-8
    host: smtp.mailtrap.io
    username: ca4036e29f3869
    password: 99cd580b1ee1cc
    port: 2525
    protocol: smtp
    
# EMAIL SERVICE CONFIGURATION
  freemarker:
    template-loader-path:
    - classpath:/templates/mail
    
    
  redis:    host: localhost
    port: 6379
    


 # Add application configuration      session:    timeout: 30m        #session timeout after 30 minutes 
app:
  config:
    default-faculty-menteeLimit: 10
    student-max-favourite-count: 3
    faculty-max-favourite-count: 4
    maximum-user-concurrent-sessions: 3
    max-failed-login-attempts: 4
    
    
client:
  config:
    routes:
      base-path: http://localhost:8080
      reset-password: ${client.config.routes.base-path}/password_reset/1234
      confirm-account: ${client.config.routes.base-path}/confirmAccount       
