
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stack-o?serverTimezone=UTC
    username: root
    password: B@naK!ng1
  
  jpa:
    hibernate:
      ddl-auto: none         # For in production, don't modify database on run
      
#   mail:
#    default-encoding: UTF-8
#    host: smtp.mailtrap.io
#    username: ca4036e29f3869
#    password: 99cd580b1ee1cc
#    port: 2525
#    protocol: smtp
      
      
# Add application configuration
    
    
client:
  config:
    routes:
      base-path: https://capmatch.ashesi.edu.gh
      

app:
  storage:
    config:
      location: TODO
      remote-storage-basepath: TODO
      profile-photo-directory: TODO
      c-v-directory: TODO
  config:
    session-idle-lifetime: 1800         # On the stage, sessions last 30 minutes when idle  