#
#logging:
#  level:
#    org.springframework: INFO
#    root: WARN
#    org.hibernate: ERROR

    
spring:
  datasource:
    url: jdbc:mysql://us-cdbr-east-06.cleardb.net/ad_1c043ebbb005492
    username: b9499340b07e3c
    password: 657b8cdd
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  redis:
    host: redis-18716.c11.us-east-1-2.ec2.cloud.redislabs.com
    port: 18716
    password: 2xWlbXoSrN9OFlWBQKksmcVB7IHs9A7g

  
  jpa:
    hibernate:
      ddl-auto: update
      
      
           
  
# MailGun SMTP Config
#  mail:
#    default-encoding: UTF-8
#    host: smtp.mailgun.org
#    username: capmatch@mg.goldenmindsdaycare.com
#    password: 331dd0708817330061d2f12af49911ac-f7d0b107-9d55ec0b
#    port: 587 
#    protocol: smtp

  # Temporarily switch to MailTrap whilst in dev
  mail:
    default-encoding: UTF-8
    host: smtp.mailtrap.io
    username: ca4036e29f3869
    password: 99cd580b1ee1cc
    port: 2525
    protocol: smtp
    
    


# Add application configuration    
client:
  config:
    routes:
      base-path: http://localhost:8080
      

app:
  config:
    session-idle-lifetime: 1200         # On the stage, sessions last 20 minutes when idle   
      