
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stack-o?serverTimezone=UTC
    username: root
    password: B@naK!ng1
  
  jpa:
    hibernate:
      ddl-auto: none         # For in production, don't modify database on run